fix usage of Image.Format to be consistent with other usages
Using Image.Format.FORMAT_RAW causes an AttributeError:

AttributeError: 'EnumTypeWrapper' object has no attribute 'FORMAT_RAW'

The usage here was inconsistent with usages in other files.