Package structure more in line with ROS recommendation for python, works on noetic (#32)
* install graph_nav_util with catkin_install_python

* fix usage of Image.Format to be consistent with other usages

Using Image.Format.FORMAT_RAW causes an AttributeError:

AttributeError: 'EnumTypeWrapper' object has no attribute 'FORMAT_RAW'

The usage here was inconsistent with usages in other files.

* fix python package structure to work on noetic

* fix shebang line in spot_ros, explicitly specify use of python3